# Generated by Django 5.2.1 on 2025-05-19 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_p_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
